# Generated by Django 4.2.2 on 2023-06-25 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('poster_link', models.CharField(max_length=1000)),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('starring', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('runtime', models.CharField(max_length=10)),
                ('released_year', models.CharField(max_length=4)),
            ],
        ),
    ]
